server/urls.py
from django.urls import path
from . import views

app_name = "server"

urlpatterns = [
    # front. page
    path("", views.index, name="home"),
    path("ajax/", views.tableajax, name="tableajax"),
    # Add computer
    path("new/computer/", views.new_computer, name="new_computer"),
    # Add secret
    path("new/secret/<int:computer_id>/", views.new_secret, name="new_secret"),
    # secret info
    path("info/secret/<int:secret_id>/", views.secret_info, name="secret_info"),
    # computerinfo
    path("info/<str:computer_id>/", views.computer_info, name="computer_info"),
    path("info/<str:serial>/", views.computer_info, name="computer_info_serial"),
    # request
    path("request/<int:secret_id>/", views.request, name="request"),
    # retrieve
    path("retrieve/<int:request_id>/", views.retrieve, name="retrieve"),
    # approve
    path("approve/<int:request_id>/", views.approve, name="approve"),
    # verify
    path("verify/<str:serial>/<str:secret_type>/", views.verify, name="verify"),
    # checkin
    path("checkin/", views.checkin, name="checkin"),
    # manage
    path("manage-requests/", views.managerequests, name="managerequests"),
]

server/models.py
from django.db import models
from django.contrib.auth.models import User, Permission
from django.contrib.contenttypes.models import ContentType
from encrypted_model_fields.fields import EncryptedCharField

from django.core.exceptions import ValidationError


# Create your models here.
class Computer(models.Model):
    # recovery_key = models.CharField(max_length=200, verbose_name="Recovery Key")
    serial = models.CharField(max_length=200, verbose_name="Serial Number", unique=True)
    username = models.CharField(max_length=200, verbose_name="User Name")
    computername = models.CharField(max_length=200, verbose_name="Computer Name")
    last_checkin = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.computername

    class Meta:
        ordering = ["serial"]
        permissions = (
            ("can_approve", ("Can approve requests to see encryption keys")),
        )


SECRET_TYPES = (
    ("recovery_key", "Recovery Key"),
    ("password", "Password"),
    ("unlock_pin", "Unlock PIN"),
)


class Secret(models.Model):
    computer = models.ForeignKey(Computer, on_delete=models.CASCADE)
    secret = EncryptedCharField(max_length=256)
    secret_type = models.CharField(
        max_length=256, choices=SECRET_TYPES, default="recovery_key"
    )
    date_escrowed = models.DateTimeField(auto_now_add=True)
    rotation_required = models.BooleanField(default=False)

    def validate_unique(self, *args, **kwargs):
        if (
            self.secret
            in [
                str(s)
                for s in self.__class__.objects.filter(
                    secret_type=self.secret_type, computer=self.computer
                )
            ]
            and not self.rotation_required
        ):
            raise ValidationError("already used")
        super(Secret, self).validate_unique(*args, **kwargs)

    def save(self, *args, **kwargs):
        self.validate_unique()
        super(Secret, self).save(*args, **kwargs)

    def __str__(self):
        return self.secret

    class Meta:
        ordering = ["-date_escrowed"]


class Request(models.Model):
    secret = models.ForeignKey(Secret, on_delete=models.PROTECT)
    # computer = models.ForeignKey(Computer, null=True, related_name='computers')
    requesting_user = models.ForeignKey(
        User, related_name="requesting_user", on_delete=models.CASCADE
    )
    approved = models.BooleanField(verbose_name="Approved?", null=True)
    auth_user = models.ForeignKey(
        User, null=True, related_name="auth_user", on_delete=models.PROTECT
    )
    reason_for_request = models.TextField()
    reason_for_approval = models.TextField(
        blank=True, null=True, verbose_name="Approval Notes"
    )
    date_requested = models.DateTimeField(auto_now_add=True)
    date_approved = models.DateTimeField(blank=True, null=True)
    current = models.BooleanField(default=True)

    def __str__(self):
        return "%s - %s" % (self.secret, self.requesting_user)

server/forms.py
from django import forms
from .models import *


class RequestForm(forms.ModelForm):
    class Meta:
        model = Request
        fields = ("reason_for_request",)


class ApproveForm(forms.ModelForm):
    # approved = forms.BooleanField()
    approved = forms.TypedChoiceField(
        coerce=lambda x: bool(int(x)),
        choices=((1, "Approved"), (0, "Denied")),
        widget=forms.RadioSelect,
        label="Approved?",
    )

    class Meta:
        model = Request
        fields = ("approved", "reason_for_approval")


class ComputerForm(forms.ModelForm):
    class Meta:
        model = Computer
        fields = ("serial", "username", "computername")


class SecretForm(forms.ModelForm):
    class Meta:
        model = Secret
        fields = ("secret_type", "secret", "computer")
        widgets = {"computer": forms.HiddenInput()}

server/views.py
import logging
from .models import *
from django.contrib.auth.decorators import login_required, permission_required
from django.template import RequestContext, Template, Context
import json
import pytz
import copy
from django.views.decorators.csrf import csrf_exempt, csrf_protect
from django.http import HttpResponse, Http404, JsonResponse
from django.contrib.auth.models import Permission, User
from django.conf import settings
from django.template.context_processors import csrf
from django.shortcuts import render, get_object_or_404, redirect
from datetime import datetime, timedelta
from django.db.models import Q
from .forms import *
from django.views.defaults import server_error
from django.core.mail import send_mail
from django.conf import settings
from django.urls import reverse
from django.utils.html import escape

# Create your views here.
logger = logging.getLogger(__name__)


##clean up old requests
def cleanup():
    how_many_days = 7
    the_requests = Request.objects.filter(
        date_approved__lte=datetime.now() - timedelta(days=how_many_days)
    ).filter(current=True)
    for the_req in the_requests:
        the_req.current = False
        the_req.save()


def get_server_version():
    current_dir = os.path.dirname(os.path.realpath(__file__))

    with open(
        os.path.join(os.path.dirname(current_dir), "fvserver", "version.plist"), "rb"
    ) as f:
        version = plistlib.load(f)
    return version["version"]


##index view
@login_required
def index(request):
    cleanup()
    # show table with all the keys
    computers = Computer.objects.none()

    if hasattr(settings, "ALL_APPROVE"):
        if settings.ALL_APPROVE == True:
            permissions = Permission.objects.all()
            permission = Permission.objects.get(codename="can_approve")
            if request.user.has_perm("server.can_approve") == False:
                request.user.user_permissions.add(permission)
                request.user.save()
    ##get the number of oustanding requests - approved equals null

    outstanding = Request.objects.filter(approved__isnull=True)
    if hasattr(settings, "APPROVE_OWN"):
        if settings.APPROVE_OWN == False:
            outstanding = outstanding.filter(~Q(requesting_user=request.user))
    c = {"user": request.user, "computers": computers, "outstanding": outstanding}
    return render(request, "server/index.html", c)


@login_required
def tableajax(request):
    """Table ajax for dataTables"""
    # Pull our variables out of the GET request
    get_data = request.GET["args"]
    get_data = json.loads(get_data)
    draw = get_data.get("draw", 0)
    start = int(get_data.get("start", 0))
    length = int(get_data.get("length", 0))
    search_value = ""
    if "search" in get_data:
        if "value" in get_data["search"]:
            search_value = get_data["search"]["value"]

    # default ordering
    order_column = 2
    order_direction = "desc"
    order_name = ""
    if "order" in get_data:
        order_column = get_data["order"][0]["column"]
        order_direction = get_data["order"][0]["dir"]
    for column in get_data.get("columns", None):
        if column["data"] == order_column:
            order_name = column["name"]
            break

    machines = Computer.objects.all().values(
        "id", "serial", "username", "computername", "last_checkin"
    )

    order_string = None
    if len(order_name) != 0:
        if order_direction == "desc":
            order_string = "-%s" % order_name
        else:
            order_string = "%s" % order_name

    if len(search_value) != 0:
        searched_machines = machines.filter(
            Q(serial__icontains=search_value)
            | Q(username__icontains=search_value)
            | Q(computername__icontains=search_value)
            | Q(last_checkin__icontains=search_value)
        )

    else:
        searched_machines = machines

    if order_name != "info_button":
        searched_machines = searched_machines.order_by(order_string)

    limited_machines = searched_machines[start : (start + length)]

    return_data = {}
    return_data["draw"] = int(draw)
    return_data["recordsTotal"] = machines.count()
    return_data["recordsFiltered"] = return_data["recordsTotal"]

    return_data["data"] = []
    settings_time_zone = None
    try:
        settings_time_zone = pytz.timezone(settings.TIME_ZONE)
    except Exception:
        pass

    for machine in limited_machines:
        if machine["last_checkin"]:
            # formatted_date = pytz.utc.localize(machine.last_checkin)
            if settings_time_zone:
                formatted_date = (
                    machine["last_checkin"]
                    .astimezone(settings_time_zone)
                    .strftime("%Y-%m-%d %H:%M %Z")
                )
            else:
                formatted_date = machine["last_checkin"].strftime("%Y-%m-%d %H:%M")
        else:
            formatted_date = ""

        serial_link = '<a href="%s">%s</a>' % (
            reverse("server:computer_info", args=[machine["id"]]),
            escape(machine["serial"]),
        )

        computername_link = '<a href="%s">%s</a>' % (
            reverse("server:computer_info", args=[machine["id"]]),
            escape(machine["computername"]),
        )

        info_button = '<a class="btn btn-info btn-xs" href="%s">Info</a>' % (
            reverse("server:computer_info", args=[machine["id"]])
        )

        list_data = [
            serial_link,
            computername_link,
            escape(machine["username"]),
            formatted_date,
            info_button,
        ]
        return_data["data"].append(list_data)

    return JsonResponse(return_data)


##view to see computer info
@login_required
def computer_info(request, computer_id=None):
    cleanup()
    try:
        computer = get_object_or_404(Computer, pk=computer_id)
    except:
        computer = get_object_or_404(Computer, serial=computer_id)
    can_request = None
    approved = None

    # Get the secrets, annotated with whethere there are approvals for them
    secrets = computer.secret_set.all().prefetch_related()

    for secret in secrets:
        secret.approved = (
            Request.objects.filter(requesting_user=request.user)
            .filter(approved=True)
            .filter(current=True)
            .filter(secret=secret)
        )
        secret.pending = (
            Request.objects.filter(requesting_user=request.user)
            .filter(approved__isnull=True)
            .filter(secret=secret)
        )

    c = {"user": request.user, "computer": computer, "secrets": secrets}

    return render(request, "server/computer_info.html", c)


@login_required
def secret_info(request, secret_id):
    cleanup()

    secret = get_object_or_404(Secret, pk=secret_id)

    computer = secret.computer

    ##check if the user has outstanding request for this
    pending = secret.request_set.filter(requesting_user=request.user).filter(
        approved__isnull=True
    )
    if pending.count() == 0:
        can_request = True
    else:
        can_request = False
    ##if it's been approved, we'll show a link to retrieve the key
    approved = (
        secret.request_set.filter(requesting_user=request.user)
        .filter(approved=True)
        .filter(current=True)
    )
    requests = secret.request_set.all()

    c = {
        "user": request.user,
        "computer": computer,
        "can_request": can_request,
        "approved": approved,
        "secret": secret,
        "requests": requests,
    }
    if approved.count() != 0:
        return render(request, "server/secret_approved_button.html", c)
    else:
        return render(request, "server/secret_request_button.html", c)


##request key view
@login_required
def request(request, secret_id):
    ##we will auto approve this if the user has the right perms
    secret = get_object_or_404(Secret, pk=secret_id)
    approver = False
    if request.user.has_perm("server.can_approve"):
        approver = True

    if approver == True:
        if hasattr(settings, "APPROVE_OWN"):
            if settings.APPROVE_OWN == False:
                approver = False
    c = {}
    c.update(csrf(request))
    if request.method == "POST":
        form = RequestForm(request.POST)
        if form.is_valid():
            new_request = form.save(commit=False)
            new_request.requesting_user = request.user
            new_request.secret = secret
            new_request.save()
            if approver:
                new_request.auth_user = request.user
                new_request.approved = True
                new_request.date_approved = datetime.now()
                new_request.save()
            else:
                # User isn't an approver, send an email to all of the approvers
                perm = Permission.objects.get(codename="can_approve")
                users = User.objects.filter(
                    Q(is_superuser=True)
                    | Q(groups__permissions=perm)
                    | Q(user_permissions=perm)
                ).distinct()

                if hasattr(settings, "HOST_NAME"):
                    server_name = settings.HOST_NAME.rstrip("/")
                else:
                    server_name = "http://crypt"
                if hasattr(settings, "SEND_EMAIL"):
                    if settings.SEND_EMAIL == True:
                        for user in users:
                            if user.email:
                                email_message = """ There has been a new key request by %s. You can review this request at %s%s
                                """ % (
                                    request.user.username,
                                    server_name,
                                    reverse("server:approve", args=[new_request.id]),
                                )
                                if hasattr(settings, "EMAIL_SENDER"):

server/templates/server/approve.html
{% extends "base.html" %}

{% load bootstrap4 %}
{% block content %}
<h1>Approve Request</h1>
<p>{{ the_request.secret.computer.computername }} ({{ the_request.secret.computer.serial }})</p>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <form action="{% url 'server:approve' the_request.id %}" method="post">{% csrf_token %}


            {% bootstrap_form form %}

        <p><button type="submit" class="btn primary btn-default">Save</button></p>

    </form>
{% endblock %}

server/templates/server/computer_info.html
{% extends "base.html" %} {% block script %}
<script type="text/javascript" charset="utf-8">
  $(document).ready(function () {
    $(".groupList").dataTable({
      //"sDom": "<'row'<'span6'l><'span6'f>r>t<'row'<'span6'i><'span6'p>>",
      // "iDisplayLength": 20,
      aLengthMenu: [
        [20, 50, -1],
        [20, 50, "All"],
      ],
      // "sPaginationType": "bootstrap",
      // "bStateSave": true,
      // "aaSorting": [[1,'asc']]
    });
  });
</script>

{% endblock %} {% block dropdown %}
<li class="nav-item">
  <a class="nav-link" href="{% url 'server:new_secret' computer.id %}"
    ><span class="glyphicon glyphicon-plus"></span> New secret</a
  >
</li>
{% endblock %} {% block nav %}
<li class="nav-item">
  <a class="nav-link" href="{% url 'server:home' %}"
    ><i class="glyphicon glyphicon-chevron-left"></i> Home</a
  >
</li>
{% endblock %} {% block content %}
<div class="row">
  <div class="col-sm-12 col-md-12">
    <h2>{{ computer.computername }}</h2>
    <h4>{{ computer.serial }}</h4>
  </div>
</div>

<div class="row">
  <div class="col-sm-4 col-md-4">
    <table class="table table-bordered table-striped table-condensed">
      <tbody>
        <tr>
          <th>Username</th>
          <td>{{ computer.username }}</td>
        </tr>
        <tr>
          <th>Computer Name</th>
          <td>{{ computer.computername }}</td>
        </tr>
        <tr>
          <th>Serial Number</th>
          <td>{{ computer.serial }}</td>
        </tr>
        <tr>
          <th>Last Checked In</th>
          <td>{{ computer.last_checkin}}</td>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="col-sm-4 col-md-4">
    {% block button %} {% endblock %}
  </div>
</div>

<div class="row">
  <div class="col-sm-12 col-md-12">
    <h3>Secrets</h3>
    <table class="table table-striped table-condensed groupList">
      <thead>
        <th>Secret Type</th>
        <th>Escrow Date</th>
        <th></th>
      </thead>
      <tbody>
        {% for secret in secrets %}
        <tr>
          <td>{{ secret.get_secret_type_display }}</td>
          <td>{{ secret.date_escrowed }}</td>
          <td>
            <a
              class="btn btn-info btn-xs"
              href="{% url 'server:secret_info' secret.id %}"
              >Info / Request</a
            >
          </td>
        </tr>

        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

{% endblock %}

server/templates/server/computer_request_button.html
{% extends "server/computer_info.html" %}
{% block button %}
        {% if not perms.server.can_approve %}
            {% if can_request %}
            <a href="{% url 'request' computer.id %}" class="btn btn-large btn-info">Request Key</a>
            {% else %}
            <button class="btn btn-disabled btn-info">Request Pending</button>
            {% endif %}
            {% else %}
            <a href="{% url 'request' computer.id %}" class="btn btn-large btn-info">Get Key</a>
        {% endif %}
{% endblock %}

server/templates/server/index.html
{% extends "base.html" %}

{% block script %}
<script type="text/javascript" charset="utf-8">
    $(document).ready(function() {

         $('.groupList').dataTable({
            "serverSide": true,
            "order": [[3,'desc']],
            columnDefs: [
                { orderable: false, targets: -1 },
                { "searchable": false, "targets": -1 }
            ],
            "ajax": {
                "contentType": "application/json",
                "url": "{% url 'server:tableajax' %}",
                "data": function ( args ) {
                    return { "args": JSON.stringify( args ) };
                }
            },
            "lengthMenu": [[20, 50, -1], [20, 50, "All"]],
            // "pageLength": {{ page_length }},
            stateSave: true,
            // "order": [2,'desc'],
            "orderMulti": false,
            "columns": [
                { "name": "serial" },
                { "name": "computername" },
                { "name": "username" },
                { "name": "last_checkin" },
                { "name": "info_button" },
            ],
        });
    } );
</script>

{% endblock %}

{% block dropdown %}
<li class="nav-item"><a class="nav-link" href="{% url 'server:new_computer' %}"><span class="glyphicon glyphicon-plus"></span> New computer</a></li>
{% endblock %}
{% block nav %}
{% if perms.server.can_approve %}
{% if outstanding.count > 0 %}
    <li class="nav-item"><a class="btn btn-info" href="{% url 'server:managerequests' %}">Approve requests</a></li>
{% else %}
<li class="nav-item"><a class="nav-link" href="{% url 'server:managerequests' %}">Approve requests</a></li>
{% endif %}
{% endif %}
{% endblock %}
{% block content %}
{% if perms.server.can_approve %}
    {% if outstanding.count > 0 %}
    <div class="alert alert-info">
        You have outstanding requests to approve.
    </div>
    {% endif %}
{% endif %}




    <table class="groupList table table-striped table-condensed">
    <thead>
        <tr>
          <th>Serial Number</th>
          <th>Computer Name</th>
          <th>User Name</th>
          <th>Last Checked In</th>
          <th></th>
        </tr>
    </thead>
    <tbody>
        {% for computer in computers.all %}
        <tr><td><a href="{% url 'server:computer_info' computer.id %}">{{ computer.serial }}</a></td><td><a href="{% url 'server:computer_info' computer.id %}">{{ computer.computername }}</a></td><td>{{ computer.username }}</td><td>{{ computer.last_checkin }}</td><td><a class="btn btn-info btn-xs" href="{% url 'server:computer_info' computer.id %}">Info</a></td></tr>
        {% endfor %}
        </tbody>
</table>

{% endblock %}

server/templates/server/manage_requests.html
{% extends "base.html" %}

{% block script %}
<script type="text/javascript" charset="utf-8">
    $(document).ready(function() {
        $('.groupList').dataTable({
            //"sDom": "<'row'<'span6'l><'span6'f>r>t<'row'<'span6'i><'span6'p>>",
            //"iDisplayLength": 20,
            "aLengthMenu": [[20, 50, -1], [20, 50, "All"]],
            //"sPaginationType": "bootstrap",
            //"bStateSave": true,
            //"aaSorting": [[1,'asc']]
        });
    } );
</script>

{% endblock %}

{% block nav %}
<li class="nav-item"><a class="nav-link" href="{% url 'server:home' %}"><i class="glyphicon glyphicon-chevron-left"></i> Home</a></li>
{% endblock %}
{% block content %}
<h3>Key Requests</h3>
<table class="groupList table table-striped table-condensed">
    <thead>
        <tr>
          <th>Serial Number</th>
          <th>Computer Name</th>
          <th>Requested By</th>
          <th>Reason for Request</th>
          <th>Date Requested</th>
          <th></th>
        </tr>
    </thead>
    <tbody>
        {% for the_request in requests %}
        <tr><td><a href="{% url 'server:approve' the_request.id %}">{{ the_request.secret.computer.serial }}</a></td><td><a href="{% url 'server:approve' the_request.id %}">{{ the_request.secret.computer.computername }}</a></td><td>{{ the_request.requesting_user }}</td><td>{{ the_request.reason_for_request }}</td><td>{{ the_request.date_requested }}</td><td><a class="btn btn-primary btn-mini" href="{% url 'server:approve' the_request.id %}">Manage</a></td></tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

server/templates/server/new_computer_form.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block content %}
<div class="row">
    <div class="col-md-4">
<h1>New Computer</h1>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <form action="{% url 'server:new_computer' %}" method="post">{% csrf_token %}


            {% bootstrap_form form %}

        <p><button type="submit" class="btn btn-primary">Add new computer</button></p>

    </form>
</div>
</div>
{% endblock %}

server/templates/server/new_secret_form.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block content %}
<div class="row">
    <div class="col-md-4">
<h1>New Secret</h1>
<h2>Computer: {{computer}}</h2>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <form action="{% url 'server:new_secret' computer.id %}" method="post">{% csrf_token %}


            {% bootstrap_form form %}

        <p><button type="submit" class="btn btn-primary">Add new secret</button></p>

    </form>
</div>
</div>
{% endblock %}

server/templates/server/request.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block content %}
<h1>Request Secret</h1>
<p>{{ secret.computer.computername }} ({{ secret.computer.serial }})</p>
<p>{{ secret.get_secret_type_display }} - {{ secret.date_escrowed }}</p>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <form action="{% url 'server:request' secret.id %}" method="post">{% csrf_token %}


            {% bootstrap_form form %}
        {% if not perms.server.can_approve %}
        <p><button type="submit" class="btn primary btn-default">Submit Request</button></p>
        {% else %}
        <p><button type="submit" class="btn primary btn-default">Retrieve Key</button></p>
        {% endif %}
    </form>
{% endblock %}

server/templates/server/retrieve.html
{% extends "base.html" %}

{% block script %}
<script type="text/javascript" charset="utf-8">
    $(document).ready(function() {
        $('.groupList').dataTable({
            //"sDom": "<'row'<'span6'l><'span6'f>r>t<'row'<'span6'i><'span6'p>>",
            // "iDisplayLength": 20,
            "aLengthMenu": [[20, 50, -1], [20, 50, "All"]],
            // "sPaginationType": "bootstrap",
            // "bStateSave": true,
            // "aaSorting": [[1,'asc']]
        });
    } );
</script>

{% endblock %}

{% block nav %}
<li class="nav-item"><a class="nav-link" href="{% url 'server:home' %}"><i class="glyphicon glyphicon-chevron-left"></i> Home</a></li>
{% endblock %}
{% block content %}
<div class="row">
    <h2>{{ computer.computername }}</h2>
    <h4>{{ computer.serial }}</h4>
</div>

<div class="row">
    <div class="col-sm-6 col-md-6">
        <p><strong>{{ the_request.secret.get_secret_type_display }}:</strong><br />
        <code>
        {% spaceless %}
        {% for char in the_request.secret.secret %}
            {% if char in "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ" %}
                <span class="letter">{{ char }}</span>
            {% elif char in "0123456789" %}
                <span class="number">{{ char }}</span>
            {% else %}
                <span class="other">{{ char }}</span>
            {% endif %}
        {% endfor %}
        {% endspaceless %}
        </code>
        </p>

        <p>This approval is valid for 7 days, after which you will need to submit another request for access.</p>
    </div>
</div>

{% endblock %}

server/templates/server/secret_approved_button.html
{% extends "server/secret_info.html" %}
{% block button %}
        {% for the_request in approved|slice:":1" %}
            <a href="{% url 'server:retrieve' the_request.id %}" class="btn btn-success btn-lg">Retrieve Key</a>

        {% endfor %}
{% endblock %}

server/templates/server/secret_info.html
{% extends "base.html" %}

{% block script %}
<script type="text/javascript" charset="utf-8">
    $(document).ready(function() {
        $('.groupList').dataTable({
            //"sDom": "<'row'<'span6'l><'span6'f>r>t<'row'<'span6'i><'span6'p>>",
            // "iDisplayLength": 20,
            "aLengthMenu": [[20, 50, -1], [20, 50, "All"]],
            // "sPaginationType": "bootstrap",
            // "bStateSave": true,
            // "aaSorting": [[1,'asc']]
        });
    } );
</script>

{% endblock %}

{% block nav %}
<li class="nav-item"><a class="nav-link" href="{% url 'server:computer_info' computer.id %}"><i class="glyphicon glyphicon-chevron-left"></i> Computer</a></li>
{% endblock %}
{% block content %}
<div class="row">
    <div class="col-sm-12 col-md-12">
    <h2>{{ computer.computername }}</h2>
    <h4>{{ computer.serial }}</h4>
    </div>
</div>

<div class="row">
    <div class="col-sm-4 col-md-4">
        <table class="table table-bordered table-striped table-condensed">
            <tbody>
            <tr><th>Username</th><td>{{ computer.username }}</td></tr>
            <tr><th>Computer Name</th><td>{{ computer.computername }}</td></tr>
            <tr><th>Serial Number</th><td>{{ computer.serial }}</td></tr>
            <tr><th>Secret Type</th><td>{{ secret.get_secret_type_display }}</td></tr>
            <tr><th>Escrow Date</th><td>{{ secret.date_escrowed }}</td></tr>
        </tbody>
        </table>
    </div>
    <div class="col-sm-4 col-md-4">
        {% block button %}
        {% endblock %}
    </div>
</div>

{% if perms.server.can_approve %}
<div class="row">
    <div class="col-sm-12 col-md-12">
    <h3>Requests</h3>
        <table class="table groupList">
        <thead>
        <tr><th>Requesting User</th>
        <th>Reason for Request</th>
        <th>Date Requested</th>
        <th>Approved By</th>
        <th>Approval Notes</th>
        <th>Date Approved</th>
        </tr></thead>
        <tbody>
            {% for the_request in requests %}
            <tr>

                <td>{{ the_request.requesting_user }}</td>
                <td>{{ the_request.reason_for_request }}</td>
                <td>{{ the_request.date_requested }}</td>
                <td>{{ the_request.auth_user }}</td>
                <td>{{ the_request.reason_for_approval }}</td>
                <td>{{ the_request.date_approved }}</td>
            </tr>

            {% endfor %}
            </tbody>
        </table>
        </div>

</div>
{% endif %}

{% endblock %}

server/templates/server/secret_request_button.html
{% extends "server/secret_info.html" %}
{% block button %}
        {% if not perms.server.can_approve %}
            {% if can_request %}
            <a href="{% url 'server:request' secret.id %}" class="btn btn-large btn-info">Request Key</a>
            {% else %}
            <button class="btn btn-disabled btn-info">Request Pending</button>
            {% endif %}
            {% else %}
            <a href="{% url 'server:request' secret.id %}" class="btn btn-large btn-info">Get Key</a>
        {% endif %}
{% endblock %}